### ISSUE TITLE
How to get the dataset?

### ISSUE THREAD

**Issue by eeg-wx2024** [lyuPang/CrossInitialization#2]
![1735034327027](https://github.com/user-attachments/assets/3b89d160-93b2-4663-ab19-fb29a2b2ced0)
Hi, I visited this webpage, but I'm unsure which dataset is used in the paper for download. Could you please clarify which one I should select?
![image](https://github.com/user-attachments/assets/3811657b-2240-47e5-b535-83467c87067b)

**Comment by lyuPang** [comment]
You can download the dataset from https://mmlab.ie.cuhk.edu.hk/projects/CelebA/CelebAMask_HQ.html.

**Comment by eeg-wx2024** [comment]
> You can download the dataset from https://mmlab.ie.cuhk.edu.hk/projects/CelebA/CelebAMask_HQ.html.

Thank you very much!

**Comment by lyuPang** [comment]
> > You can download the dataset from https://mmlab.ie.cuhk.edu.hk/projects/CelebA/CelebAMask_HQ.html.
> 
> Thank you very much!

You're welcome!
